-- =========================================================
-- MINI PROJECT
-- SALES ANALYTICS DASHBOARD SYSTEM
-- =========================================================

-- =========================================================
-- PROJECT OVERVIEW
-- =========================================================
-- This project simulates a real-world sales analytics system
-- used by companies to analyze:
--
-- 1. Revenue performance
-- 2. Product category sales
-- 3. Region-wise business growth
-- 4. KPI reporting
-- 5. Business summaries
--
-- Concepts Used:
-- - Aggregate Functions
-- - GROUP BY
-- - HAVING
-- - Business Analytics Queries
--
-- This type of SQL project is commonly used in:
-- - Data Analyst roles
-- - Dashboard systems
-- - Business Intelligence
-- - Sales Reporting
-- =========================================================



-- =========================================================
-- STEP 1: CREATE TABLE
-- =========================================================

CREATE TABLE company_sales (
    sale_id INT,
    product_name VARCHAR(50),
    category VARCHAR(50),
    region VARCHAR(50),
    sales_amount INT,
    quantity INT
);



-- =========================================================
-- TABLE UNDERSTANDING
-- =========================================================
-- sale_id       -> Unique ID for each sale
-- product_name  -> Name of product
-- category      -> Product category
-- region        -> Sales region
-- sales_amount  -> Revenue generated
-- quantity      -> Units sold
-- =========================================================



-- =========================================================
-- STEP 2: INSERT DATA
-- =========================================================

INSERT INTO company_sales
VALUES
(1, 'Laptop', 'Electronics', 'North', 70000, 2),
(2, 'Phone', 'Electronics', 'South', 50000, 4),
(3, 'Shoes', 'Fashion', 'West', 4000, 10),
(4, 'Watch', 'Accessories', 'North', 8000, 3),
(5, 'Rice Bag', 'Grocery', 'East', 3000, 12),
(6, 'Tablet', 'Electronics', 'South', 60000, 2),
(7, 'Jacket', 'Fashion', 'West', 5000, 6),
(8, 'Headphones', 'Electronics', 'North', 6000, 8),
(9, 'Milk', 'Grocery', 'East', 2000, 15),
(10, 'Bag', 'Fashion', 'South', 3500, 7);



-- =========================================================
-- STEP 3: VIEW COMPLETE DATA
-- =========================================================
-- Business Use Case:
-- Used to verify inserted records before analysis
-- =========================================================

SELECT *
FROM company_sales;



-- =========================================================
-- STEP 4: TOTAL COMPANY REVENUE
-- =========================================================
-- Business Use Case:
-- Calculate overall company revenue
-- Used in:
-- - KPI dashboards
-- - Revenue reports
-- - Business performance tracking
-- =========================================================

SELECT
    SUM(sales_amount) AS total_revenue
FROM company_sales;



-- =========================================================
-- STEP 5: TOTAL NUMBER OF ORDERS
-- =========================================================
-- Business Use Case:
-- Calculate total transactions/orders
-- =========================================================

SELECT
    COUNT(*) AS total_orders
FROM company_sales;



-- =========================================================
-- STEP 6: AVERAGE SALES AMOUNT
-- =========================================================
-- Business Use Case:
-- Analyze average order value
-- Helps companies understand customer spending behavior
-- =========================================================

SELECT
    AVG(sales_amount) AS average_sales
FROM company_sales;



-- =========================================================
-- STEP 7: HIGHEST SALE
-- =========================================================
-- Business Use Case:
-- Identify highest transaction value
-- =========================================================

SELECT
    MAX(sales_amount) AS highest_sale
FROM company_sales;



-- =========================================================
-- STEP 8: LOWEST SALE
-- =========================================================
-- Business Use Case:
-- Identify smallest transaction value
-- =========================================================

SELECT
    MIN(sales_amount) AS lowest_sale
FROM company_sales;



-- =========================================================
-- STEP 9: CATEGORY-WISE SALES ANALYSIS
-- =========================================================
-- Business Use Case:
-- Analyze total revenue generated by each category
--
-- Helps companies identify:
-- - Best performing categories
-- - Weak categories
-- - Revenue contribution
-- =========================================================

SELECT
    category,
    SUM(sales_amount) AS total_sales
FROM company_sales
GROUP BY category;



-- =========================================================
-- STEP 10: REGION-WISE SALES REPORT
-- =========================================================
-- Business Use Case:
-- Analyze business performance region-wise
--
-- This type of query is heavily used in:
-- - Sales dashboards
-- - Regional reports
-- - Performance tracking systems
-- =========================================================

SELECT
    region,
    COUNT(*) AS total_orders,
    SUM(sales_amount) AS total_sales,
    AVG(sales_amount) AS average_sales
FROM company_sales
GROUP BY region;



-- =========================================================
-- STEP 11: CATEGORY-WISE KPI REPORT
-- =========================================================
-- Business Use Case:
-- Generate category-level business KPIs
--
-- KPIs Included:
-- - Total Orders
-- - Total Revenue
-- - Average Sales
-- - Highest Sale
-- - Lowest Sale
--
-- This is a REAL Data Analyst style query
-- =========================================================

SELECT
    category,
    COUNT(*) AS total_orders,
    SUM(sales_amount) AS total_revenue,
    AVG(sales_amount) AS average_sales,
    MAX(sales_amount) AS highest_sale,
    MIN(sales_amount) AS lowest_sale
FROM company_sales
GROUP BY category;



-- =========================================================
-- STEP 12: HIGH REVENUE CATEGORIES
-- =========================================================
-- Business Use Case:
-- Identify categories generating high revenue
--
-- HAVING is used because filtering happens
-- AFTER aggregation
-- =========================================================

SELECT
    category,
    SUM(sales_amount) AS total_sales
FROM company_sales
GROUP BY category
HAVING SUM(sales_amount) > 10000;



-- =========================================================
-- STEP 13: REGION-WISE KPI DASHBOARD
-- =========================================================
-- Business Use Case:
-- Generate regional business performance summary
-- =========================================================

SELECT
    region,
    COUNT(*) AS total_orders,
    SUM(sales_amount) AS total_revenue,
    AVG(sales_amount) AS average_sales,
    MAX(sales_amount) AS highest_sale,
    MIN(sales_amount) AS lowest_sale
FROM company_sales
GROUP BY region;



-- =========================================================
-- STEP 14: TOP PERFORMING CATEGORY
-- =========================================================
-- Business Use Case:
-- Find category with highest revenue
--
-- Concepts Used:
-- - GROUP BY
-- - SUM()
-- - ORDER BY
-- - LIMIT
-- =========================================================

SELECT
    category,
    SUM(sales_amount) AS total_sales
FROM company_sales
GROUP BY category
ORDER BY total_sales DESC
LIMIT 1;



-- =========================================================
-- STEP 15: SALES QUANTITY ANALYSIS
-- =========================================================
-- Business Use Case:
-- Analyze total products sold category-wise
-- =========================================================

SELECT
    category,
    SUM(quantity) AS total_quantity_sold
FROM company_sales
GROUP BY category;



-- =========================================================
-- FINAL PROJECT UNDERSTANDING
-- =========================================================
-- This project demonstrates:
--
-- 1. Aggregate Functions
-- 2. GROUP BY analytics
-- 3. HAVING filtering
-- 4. KPI calculations
-- 5. Business reporting
-- 6. Dashboard-style queries
--
-- Skills Developed:
-- - SQL analytics
-- - Business analysis
-- - Reporting logic
-- - KPI generation
-- - Data summarization
--
-- This project represents a beginner-level
-- real-world Data Analyst SQL project.
-- =========================================================